package dev.mcshield.obf.modules;

import dev.mcshield.obf.config.ObfConfig;
import dev.mcshield.obf.io.ClassEntry;
import dev.mcshield.obf.io.JarModel;
import dev.mcshield.obf.util.Wildcard;

import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Random;

public final class CStyleDecoy {
    private final ObfConfig config;
    private final Random random;

    public CStyleDecoy(ObfConfig config, long seed) {
        this.config = config;
        this.random = new Random(seed ^ 0xC0DEC0DEL);
    }

    public int apply(JarModel model) {
        if (!config.enabled("fakeC", false)) return 0;
        int count = 0;
        String source = config.string("fakeC.sourceFile", "plugin_native.c");
        for (ClassEntry ce : model.classes.values()) {
            String fqn = ce.node.name.replace('/', '.');
            if (Wildcard.any(ce.node.name, config.list("fakeC.skipClasses")) || Wildcard.any(fqn, config.list("fakeC.skipClasses"))) continue;
            ce.node.sourceFile = source;
            ce.node.sourceDebug = "SMAP\n" + source + "\nC\n*S C\n*F\n+ 1 " + source + "\n" + source + "\n*L\n1#1,4096:1\n*E";
            count++;
        }
        return count;
    }

    public Map<String, byte[]> resources() {
        Map<String, byte[]> out = new LinkedHashMap<>();
        if (!config.enabled("fakeC", false) || !config.bool("fakeC.injectResource", true)) return out;
        int files = Math.max(1, config.integer("fakeC.resources", 2));
        for (int i = 0; i < files; i++) {
            String name = "META-INF/.mcshield/native/" + Integer.toHexString(random.nextInt()) + ".c";
            out.put(name, fakeCSource(i).getBytes(StandardCharsets.UTF_8));
        }
        return out;
    }

    private String fakeCSource(int index) {
        int a = random.nextInt();
        int b = random.nextInt();
        return "/* decoy native view - generated by McShield */\n"
                + "#include <jni.h>\n"
                + "#define MC_PTR(x) ((uintptr_t)(x) ^ 0x" + Integer.toHexString(a) + ")\n"
                + "static volatile int guard_" + index + " = 0x" + Integer.toHexString(b) + ";\n"
                + "JNIEXPORT jint JNICALL Java_mcshield_decoy_entry(JNIEnv *env, jobject self, jint x) {\n"
                + "    int y = (x ^ guard_" + index + ") + (int)MC_PTR(self);\n"
                + "    return (y << 3) ^ (y >> 1);\n"
                + "}\n";
    }
}
